name: Optimize resource pack
on: [push]
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: copy license
        run: cp ./LICENSE ./pack/LICENSE.txt
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          path: pack
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          path: pack.zip