name: publish to modrinth

on:
  release:
    types: [ published ]

jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: copy license
        run: cp ./LICENSE ./pack/LICENSE.txt
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          path: pack
          artifact_name: Resource Pack

  publish:
    runs-on: ubuntu-latest
    needs: packsquash
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Resource Pack
          path: download

      - uses: Kir-Antipov/mc-publish@v3.1
        with:
          modrinth-id: 12Zt1lua
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          loaders: minecraft
          game-versions: 1.19.2
          modrinth-dependencies: |
            applied-energistics-2-wireless-terminals | depends | 12.8.4-fabric
            applied-energistics-2-wireless-terminals | depends | 12.5.1-forge
            ae2 | depends | 12.8.4
          version: ${{ env.version_name }}
          name: ${{ env.version_name }}
          files-primary: download/Resource Pack.zip
          files-secondary: ""